# Generated by Django 3.2 on 2023-05-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230512_1815'),
        ('reviews', '0003_auto_20230511_1012'),
    ]

    operations = [
    ]
